# arxivの学問領域の指定
subject: 'q-bio'

# 検索キーワード
keywords:
        Nucreotide excision: 3
        DNA damage repair: 3
        DNA damage: 2
        smoking: 2
        cigarette: 2
        tobacco: 2
        
